apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkus-demo
  description: A Quarkus application
  labels:
    department: hr
  annotations:
    backstage.io/kubernetes-id: quarkus-demo
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage-collection/quarkus-demo
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: api
  system: system:default/examples
  lifecycle: production
  owner: group:default/developers
